"""
UI - Componentes de interfaz de usuario
"""

from .ui import (
    SCREEN_WIDTH, SCREEN_HEIGHT, FPS,
    WHITE, BLACK, RED, GREEN, BLUE, YELLOW, CYAN, MAGENTA, ORANGE, GRAY,
    PLAYER_SPEED, ENEMY_SPEED_BASE, PROJECTILE_SPEED, METEOR_SPEED_BASE,
    PLAYER_LIVES, MAX_ENEMIES_ON_SCREEN, METEOR_SPAWN_INTERVAL,
    POINTS_ENEMY, POINTS_METEOR, POINTS_BOSS_1, POINTS_BOSS_2, POINTS_BOSS_3,
    MAX_TOP_SCORES,
    load_font, load_image
)

from .intro_screen import IntroScreen

__all__ = [
    'SCREEN_WIDTH', 'SCREEN_HEIGHT', 'FPS',
    'WHITE', 'BLACK', 'RED', 'GREEN', 'BLUE', 'YELLOW', 'CYAN', 'MAGENTA', 'ORANGE', 'GRAY',
    'PLAYER_SPEED', 'ENEMY_SPEED_BASE', 'PROJECTILE_SPEED', 'METEOR_SPEED_BASE',
    'PLAYER_LIVES', 'MAX_ENEMIES_ON_SCREEN', 'METEOR_SPAWN_INTERVAL',
    'POINTS_ENEMY', 'POINTS_METEOR', 'POINTS_BOSS_1', 'POINTS_BOSS_2', 'POINTS_BOSS_3',
    'MAX_TOP_SCORES',
    'load_font', 'load_image',
    'IntroScreen'
]
